export const CARD_ASSETS: Record<string, string> = {
  agents: '/cards/agents.svg',
  architecture: '/cards/architecture.svg',
  bots: '/cards/bots.svg',
  creative: '/cards/creative.svg',
  cryptographic: '/cards/cryptographic.svg',
  data: '/cards/data.svg',
  desktop: '/cards/desktop.svg',
  devops: '/cards/devops.svg',
  devtools: '/cards/devtools.svg',
  frontend: '/cards/frontend.svg',
  gatekeeper: '/cards/gatekeeper.svg',
  lab: '/cards/lab.svg',
  memory: '/cards/memory.svg',
  performance: '/cards/performance.svg',
  research: '/cards/research.svg',
  reviewer: '/cards/reviewer.svg',
  rust: '/cards/rust.svg',
  security: '/cards/security.svg',
  systems: '/cards/systems.svg',
  testing: '/cards/testing.svg',
  unreal: '/cards/unreal.svg',
  writer: '/cards/writer.svg',
};
