// ========== MOCK DATA ==========
// All 22 FrameShift personas with realistic data

import type { PackRecord, AuthorRecord } from './types';

export const MOCK_PACKS: PackRecord[] = [
  {
    name: 'agents',
    display_name: 'Agents',
    description: 'Autonomous agent orchestration persona. Specializes in multi-step task decomposition, tool chaining, and self-directed execution loops with robust error recovery.',
    author_handle: 'ghost-frame',
    version: '1.4.2',
    tags: ['agents', 'orchestration', 'automation'],
    conformance_score: 97,
    downloads: 14820,
    published_at: '2024-11-01T00:00:00Z',
    updated_at: '2025-03-15T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '1.4.2', published_at: '2025-03-15T00:00:00Z', changelog: 'Improved loop detection and exit conditions', downloads: 2100 },
      { version: '1.3.0', published_at: '2025-01-10T00:00:00Z', changelog: 'Added parallel subagent spawning', downloads: 5400 },
      { version: '1.2.1', published_at: '2024-12-01T00:00:00Z', changelog: 'Fix: deadlock in recursive tool calls', downloads: 7320 },
    ],
    capabilities: {
      tools: ['spawn_subagent', 'task_decompose', 'loop_guard', 'checkpoint'],
      memory: true,
      reasoning: 'chain-of-thought',
      specialties: ['multi-agent', 'orchestration', 'task planning'],
    },
  },
  {
    name: 'architecture',
    display_name: 'Architecture',
    description: 'Systems design and architecture persona. Draws diagrams in your head, proposes tradeoffs, identifies bottlenecks, and enforces SOLID principles across codebases.',
    author_handle: 'ghost-frame',
    version: '2.1.0',
    tags: ['architecture', 'systems', 'design'],
    conformance_score: 99,
    downloads: 22310,
    published_at: '2024-09-20T00:00:00Z',
    updated_at: '2025-04-02T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '2.1.0', published_at: '2025-04-02T00:00:00Z', changelog: 'Added microservices pattern library', downloads: 3100 },
      { version: '2.0.0', published_at: '2025-01-15T00:00:00Z', changelog: 'Major rework: event-driven architecture support', downloads: 9200 },
      { version: '1.9.3', published_at: '2024-11-20T00:00:00Z', changelog: 'ADR template improvements', downloads: 10010 },
    ],
    capabilities: {
      tools: ['diagram_gen', 'dependency_map', 'tradeoff_matrix'],
      memory: true,
      reasoning: 'structured-analysis',
      specialties: ['distributed systems', 'microservices', 'event-driven', 'monolith migration'],
    },
  },
  {
    name: 'bots',
    display_name: 'Bots',
    description: 'Chatbot and conversational AI persona. Handles dialog flow design, intent recognition scaffolding, personality tuning, and multi-turn context management.',
    author_handle: 'ghost-frame',
    version: '1.2.0',
    tags: ['bots', 'nlp', 'conversation'],
    conformance_score: 91,
    downloads: 8740,
    published_at: '2024-12-05T00:00:00Z',
    updated_at: '2025-02-28T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '1.2.0', published_at: '2025-02-28T00:00:00Z', changelog: 'Slot-filling dialog support', downloads: 1800 },
      { version: '1.1.0', published_at: '2025-01-05T00:00:00Z', changelog: 'Persona injection system', downloads: 3200 },
      { version: '1.0.0', published_at: '2024-12-05T00:00:00Z', changelog: 'Initial release', downloads: 3740 },
    ],
    capabilities: {
      tools: ['intent_detect', 'slot_fill', 'dialog_state'],
      memory: true,
      reasoning: 'conversational',
      specialties: ['chatbot design', 'NLU', 'dialog management'],
    },
  },
  {
    name: 'creative',
    display_name: 'Creative',
    description: 'Creative writing and ideation persona. World-building, narrative arcs, character voice, poetic form, and lateral thinking for generative content pipelines.',
    author_handle: 'ghost-frame',
    version: '3.0.1',
    tags: ['creative', 'writing', 'ideation'],
    conformance_score: 88,
    downloads: 31500,
    published_at: '2024-08-10T00:00:00Z',
    updated_at: '2025-05-01T00:00:00Z',
    is_new: true,
    extends: undefined,
    versions: [
      { version: '3.0.1', published_at: '2025-05-01T00:00:00Z', changelog: 'Improved lyrical density controls', downloads: 1200 },
      { version: '3.0.0', published_at: '2025-04-01T00:00:00Z', changelog: 'Narrative structure overhaul', downloads: 4400 },
      { version: '2.8.0', published_at: '2025-02-10T00:00:00Z', changelog: 'Added genre-specific voice packs', downloads: 25900 },
    ],
    capabilities: {
      memory: true,
      reasoning: 'lateral',
      specialties: ['fiction', 'world-building', 'poetry', 'screenwriting', 'copywriting'],
    },
  },
  {
    name: 'cryptographic',
    display_name: 'Cryptographic',
    description: 'Cryptography and security protocol persona. Constant-time implementations, key management advice, protocol analysis, and vulnerability identification in crypto code.',
    author_handle: 'ghost-frame',
    version: '1.6.0',
    tags: ['cryptographic', 'security', 'protocols'],
    conformance_score: 100,
    downloads: 9810,
    published_at: '2024-10-15T00:00:00Z',
    updated_at: '2025-03-30T00:00:00Z',
    is_new: false,
    extends: 'security',
    versions: [
      { version: '1.6.0', published_at: '2025-03-30T00:00:00Z', changelog: 'Post-quantum algorithm awareness', downloads: 2100 },
      { version: '1.5.0', published_at: '2025-01-20T00:00:00Z', changelog: 'ZK-proof scaffolding', downloads: 3900 },
      { version: '1.4.1', published_at: '2024-12-10T00:00:00Z', changelog: 'Side-channel attack detection heuristics', downloads: 3810 },
    ],
    capabilities: {
      tools: ['timing_analysis', 'entropy_check', 'protocol_verify'],
      memory: false,
      reasoning: 'formal',
      specialties: ['TLS', 'RSA', 'ECC', 'ZK proofs', 'constant-time code'],
    },
  },
  {
    name: 'data',
    display_name: 'Data',
    description: 'Data engineering and analytics persona. Pipeline construction, schema design, SQL optimization, ETL patterns, and DataFrame manipulation with attention to correctness.',
    author_handle: 'ghost-frame',
    version: '2.3.0',
    tags: ['data', 'analytics', 'sql'],
    conformance_score: 95,
    downloads: 18920,
    published_at: '2024-09-05T00:00:00Z',
    updated_at: '2025-04-10T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '2.3.0', published_at: '2025-04-10T00:00:00Z', changelog: 'DuckDB and Polars support', downloads: 2800 },
      { version: '2.2.0', published_at: '2025-02-01T00:00:00Z', changelog: 'Streaming pipeline patterns', downloads: 7100 },
      { version: '2.1.0', published_at: '2024-11-15T00:00:00Z', changelog: 'dbt integration helpers', downloads: 9020 },
    ],
    capabilities: {
      tools: ['sql_explain', 'schema_lint', 'pipeline_trace'],
      memory: true,
      reasoning: 'analytical',
      specialties: ['SQL', 'Spark', 'dbt', 'Polars', 'data modeling', 'ETL'],
    },
  },
  {
    name: 'desktop',
    display_name: 'Desktop',
    description: 'Desktop application development persona. Native UI patterns, platform APIs, accessibility compliance, packaging, and cross-platform compatibility for Electron, Tauri, and native frameworks.',
    author_handle: 'ghost-frame',
    version: '1.1.0',
    tags: ['desktop', 'native', 'ui'],
    conformance_score: 89,
    downloads: 6230,
    published_at: '2025-01-10T00:00:00Z',
    updated_at: '2025-04-20T00:00:00Z',
    is_new: true,
    extends: undefined,
    versions: [
      { version: '1.1.0', published_at: '2025-04-20T00:00:00Z', changelog: 'Tauri v2 support', downloads: 1500 },
      { version: '1.0.0', published_at: '2025-01-10T00:00:00Z', changelog: 'Initial release', downloads: 4730 },
    ],
    capabilities: {
      frameworks: ['Electron', 'Tauri', 'Qt', 'GTK', 'WinUI'],
      memory: false,
      reasoning: 'platform-aware',
      specialties: ['IPC', 'system tray', 'native menus', 'auto-update', 'signing'],
    },
  },
  {
    name: 'devops',
    display_name: 'DevOps',
    description: 'DevOps and infrastructure persona. CI/CD pipeline design, container orchestration, infrastructure-as-code, observability stacks, and incident runbook generation.',
    author_handle: 'ghost-frame',
    version: '2.5.1',
    tags: ['devops', 'infrastructure', 'ci-cd'],
    conformance_score: 96,
    downloads: 25600,
    published_at: '2024-08-20T00:00:00Z',
    updated_at: '2025-05-10T00:00:00Z',
    is_new: true,
    extends: undefined,
    versions: [
      { version: '2.5.1', published_at: '2025-05-10T00:00:00Z', changelog: 'Dagger.io pipeline support', downloads: 900 },
      { version: '2.5.0', published_at: '2025-04-01T00:00:00Z', changelog: 'ArgoCD and FluxCD workflows', downloads: 5200 },
      { version: '2.4.0', published_at: '2025-02-15T00:00:00Z', changelog: 'Terraform 1.8 patterns', downloads: 19500 },
    ],
    capabilities: {
      tools: ['k8s_validate', 'pipeline_lint', 'iac_diff'],
      memory: true,
      reasoning: 'operational',
      specialties: ['Kubernetes', 'Terraform', 'GitHub Actions', 'Prometheus', 'Grafana'],
    },
  },
  {
    name: 'devtools',
    display_name: 'DevTools',
    description: 'Developer tooling persona. CLI design, REPL ergonomics, language server protocol implementations, debugger integrations, and build system optimization.',
    author_handle: 'ghost-frame',
    version: '1.8.0',
    tags: ['devtools', 'cli', 'lsp'],
    conformance_score: 93,
    downloads: 11200,
    published_at: '2024-10-01T00:00:00Z',
    updated_at: '2025-03-25T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '1.8.0', published_at: '2025-03-25T00:00:00Z', changelog: 'LSP hover provider patterns', downloads: 2100 },
      { version: '1.7.0', published_at: '2025-01-05T00:00:00Z', changelog: 'DAP debugger adapter support', downloads: 4300 },
      { version: '1.6.0', published_at: '2024-11-10T00:00:00Z', changelog: 'Shell completion generation', downloads: 4800 },
    ],
    capabilities: {
      tools: ['lsp_scaffold', 'cli_generator', 'dap_adapter'],
      memory: false,
      reasoning: 'ergonomic',
      specialties: ['LSP', 'DAP', 'clap/cobra CLIs', 'tree-sitter', 'build systems'],
    },
  },
  {
    name: 'frontend',
    display_name: 'Frontend',
    description: 'Frontend engineering persona. React, Vue, and Svelte patterns, CSS architecture, performance budgets, accessibility audits, and design system implementation.',
    author_handle: 'ghost-frame',
    version: '3.2.0',
    tags: ['frontend', 'react', 'css'],
    conformance_score: 98,
    downloads: 38900,
    published_at: '2024-07-15T00:00:00Z',
    updated_at: '2025-05-12T00:00:00Z',
    is_new: true,
    extends: undefined,
    versions: [
      { version: '3.2.0', published_at: '2025-05-12T00:00:00Z', changelog: 'React 19 concurrent features', downloads: 1200 },
      { version: '3.1.0', published_at: '2025-03-01T00:00:00Z', changelog: 'Tailwind v4 migration guide', downloads: 12000 },
      { version: '3.0.0', published_at: '2025-01-01T00:00:00Z', changelog: 'Next.js App Router patterns', downloads: 25700 },
    ],
    capabilities: {
      frameworks: ['React', 'Vue', 'Svelte', 'Next.js', 'Astro'],
      memory: true,
      reasoning: 'component-driven',
      specialties: ['accessibility', 'Core Web Vitals', 'CSS-in-JS', 'design systems'],
    },
  },
  {
    name: 'gatekeeper',
    display_name: 'Gatekeeper',
    description: 'Access control and policy persona. RBAC/ABAC design, OAuth flows, zero-trust architecture, API gateway configuration, and audit trail implementation.',
    author_handle: 'ghost-frame',
    version: '1.3.0',
    tags: ['security', 'auth', 'policy'],
    conformance_score: 99,
    downloads: 7650,
    published_at: '2024-11-20T00:00:00Z',
    updated_at: '2025-04-05T00:00:00Z',
    is_new: false,
    extends: 'security',
    versions: [
      { version: '1.3.0', published_at: '2025-04-05T00:00:00Z', changelog: 'OPA policy generation', downloads: 1400 },
      { version: '1.2.0', published_at: '2025-01-25T00:00:00Z', changelog: 'OIDC PKCE flow templates', downloads: 3200 },
      { version: '1.1.0', published_at: '2024-12-01T00:00:00Z', changelog: 'Audit log schema standards', downloads: 3050 },
    ],
    capabilities: {
      tools: ['policy_lint', 'rbac_diagram', 'token_validate'],
      memory: true,
      reasoning: 'policy-formal',
      specialties: ['OAuth 2.0', 'OIDC', 'RBAC', 'ABAC', 'OPA', 'Casbin'],
    },
  },
  {
    name: 'lab',
    display_name: 'Lab',
    description: 'Experimental research and prototyping persona. Hypothesis-driven development, quick-and-dirty proofs of concept, benchmark harnesses, and exploratory data analysis.',
    author_handle: 'ghost-frame',
    version: '1.0.4',
    tags: ['research', 'prototyping', 'experiments'],
    conformance_score: 82,
    downloads: 5100,
    published_at: '2025-01-20T00:00:00Z',
    updated_at: '2025-04-15T00:00:00Z',
    is_new: true,
    extends: 'research',
    versions: [
      { version: '1.0.4', published_at: '2025-04-15T00:00:00Z', changelog: 'Jupyter notebook scaffolding', downloads: 900 },
      { version: '1.0.3', published_at: '2025-03-01T00:00:00Z', changelog: 'Benchmark harness templates', downloads: 1800 },
      { version: '1.0.0', published_at: '2025-01-20T00:00:00Z', changelog: 'Initial release', downloads: 2400 },
    ],
    capabilities: {
      tools: ['hypothesis_log', 'bench_runner', 'eda_scaffold'],
      memory: true,
      reasoning: 'exploratory',
      specialties: ['rapid prototyping', 'EDA', 'benchmarking', 'Jupyter', 'statistical testing'],
    },
  },
  {
    name: 'memory',
    display_name: 'Memory',
    description: 'Persistent context and memory management persona. Designs embedding pipelines, vector store schemas, retrieval strategies, and long-horizon context compression.',
    author_handle: 'ghost-frame',
    version: '2.0.0',
    tags: ['memory', 'rag', 'embeddings'],
    conformance_score: 94,
    downloads: 12400,
    published_at: '2024-10-10T00:00:00Z',
    updated_at: '2025-03-20T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '2.0.0', published_at: '2025-03-20T00:00:00Z', changelog: 'Hierarchical memory indexing', downloads: 2400 },
      { version: '1.5.0', published_at: '2025-01-01T00:00:00Z', changelog: 'HyDE retrieval strategy', downloads: 5500 },
      { version: '1.0.0', published_at: '2024-10-10T00:00:00Z', changelog: 'Initial release', downloads: 4500 },
    ],
    capabilities: {
      tools: ['embed_pipeline', 'chunk_strategy', 'retrieval_eval'],
      memory: true,
      reasoning: 'retrieval-augmented',
      specialties: ['RAG', 'vector databases', 'context compression', 'embedding models'],
    },
  },
  {
    name: 'performance',
    display_name: 'Performance',
    description: 'Performance engineering persona. Profiling-driven optimization, cache strategies, algorithmic complexity analysis, lock contention diagnosis, and latency budget allocation.',
    author_handle: 'ghost-frame',
    version: '1.7.0',
    tags: ['performance', 'profiling', 'optimization'],
    conformance_score: 96,
    downloads: 16800,
    published_at: '2024-09-15T00:00:00Z',
    updated_at: '2025-04-08T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '1.7.0', published_at: '2025-04-08T00:00:00Z', changelog: 'Flamegraph interpretation mode', downloads: 2300 },
      { version: '1.6.0', published_at: '2025-02-01T00:00:00Z', changelog: 'Memory allocator analysis', downloads: 6800 },
      { version: '1.5.0', published_at: '2024-11-01T00:00:00Z', changelog: 'Async runtime profiling', downloads: 7700 },
    ],
    capabilities: {
      tools: ['flamegraph', 'alloc_trace', 'cache_analysis', 'latency_budget'],
      memory: false,
      reasoning: 'measurement-driven',
      specialties: ['perf', 'valgrind', 'tokio-console', 'criterion', 'SIMD'],
    },
  },
  {
    name: 'research',
    display_name: 'Research',
    description: 'Technical research and literature review persona. Summarizes papers, synthesizes prior art, extracts implementation insights, and structures findings into actionable reports.',
    author_handle: 'ghost-frame',
    version: '1.5.0',
    tags: ['research', 'ml', 'literature'],
    conformance_score: 90,
    downloads: 9200,
    published_at: '2024-10-20T00:00:00Z',
    updated_at: '2025-03-10T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '1.5.0', published_at: '2025-03-10T00:00:00Z', changelog: 'ArXiv digest integration', downloads: 1900 },
      { version: '1.4.0', published_at: '2025-01-01T00:00:00Z', changelog: 'Citation graph traversal', downloads: 3800 },
      { version: '1.3.0', published_at: '2024-11-15T00:00:00Z', changelog: 'Empirical claim extraction', downloads: 3500 },
    ],
    capabilities: {
      tools: ['paper_summary', 'claim_extract', 'prior_art_search'],
      memory: true,
      reasoning: 'academic',
      specialties: ['ML papers', 'systems research', 'survey synthesis', 'reproducibility analysis'],
    },
  },
  {
    name: 'reviewer',
    display_name: 'Reviewer',
    description: 'Code review persona. Identifies logical errors, security issues, style drift, missing tests, and brittle abstractions. Produces structured review comments with severity levels.',
    author_handle: 'ghost-frame',
    version: '2.2.0',
    tags: ['review', 'quality', 'testing'],
    conformance_score: 97,
    downloads: 20100,
    published_at: '2024-08-30T00:00:00Z',
    updated_at: '2025-04-18T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '2.2.0', published_at: '2025-04-18T00:00:00Z', changelog: 'Severity scoring matrix', downloads: 2800 },
      { version: '2.1.0', published_at: '2025-02-10T00:00:00Z', changelog: 'Structured comment templates', downloads: 8400 },
      { version: '2.0.0', published_at: '2024-12-01T00:00:00Z', changelog: 'Multi-language support', downloads: 8900 },
    ],
    capabilities: {
      tools: ['static_lint', 'complexity_score', 'security_scan', 'test_coverage_check'],
      memory: false,
      reasoning: 'critical',
      specialties: ['SAST', 'code smell detection', 'API surface review', 'dependency audit'],
    },
  },
  {
    name: 'rust',
    display_name: 'Rust',
    description: 'Rust systems programming persona. Ownership models, async runtimes, unsafe auditing, macro design, crate ecosystem navigation, and performance-conscious idiomatic Rust.',
    author_handle: 'ghost-frame',
    version: '2.8.0',
    tags: ['rust', 'systems', 'performance'],
    conformance_score: 100,
    downloads: 29400,
    published_at: '2024-07-01T00:00:00Z',
    updated_at: '2025-05-08T00:00:00Z',
    is_new: true,
    extends: undefined,
    versions: [
      { version: '2.8.0', published_at: '2025-05-08T00:00:00Z', changelog: 'Rust 2024 edition patterns', downloads: 1800 },
      { version: '2.7.0', published_at: '2025-03-01T00:00:00Z', changelog: 'async-trait zero-cost patterns', downloads: 9200 },
      { version: '2.6.0', published_at: '2025-01-01T00:00:00Z', changelog: 'Tokio and monoio runtime guide', downloads: 18400 },
    ],
    capabilities: {
      languages: ['Rust'],
      tools: ['cargo_audit', 'miri_check', 'flamegraph'],
      memory: false,
      reasoning: 'ownership-aware',
      specialties: ['async Rust', 'unsafe', 'proc-macros', 'FFI', 'WASM', 'embedded'],
    },
  },
  {
    name: 'security',
    display_name: 'Security',
    description: 'Application security persona. Threat modeling, OWASP coverage, fuzzing strategy, dependency vulnerability triage, and secure-by-default API design.',
    author_handle: 'ghost-frame',
    version: '2.4.0',
    tags: ['security', 'appsec', 'threats'],
    conformance_score: 99,
    downloads: 24700,
    published_at: '2024-08-05T00:00:00Z',
    updated_at: '2025-04-22T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '2.4.0', published_at: '2025-04-22T00:00:00Z', changelog: 'AI supply chain threat models', downloads: 2500 },
      { version: '2.3.0', published_at: '2025-02-05T00:00:00Z', changelog: 'SBOM generation guidance', downloads: 9100 },
      { version: '2.2.0', published_at: '2024-11-25T00:00:00Z', changelog: 'OWASP Top 10 2024 update', downloads: 13100 },
    ],
    capabilities: {
      tools: ['threat_model', 'dep_audit', 'fuzz_harness', 'secret_scan'],
      memory: true,
      reasoning: 'adversarial',
      specialties: ['OWASP', 'STRIDE', 'fuzzing', 'SBOM', 'CVE triage'],
    },
  },
  {
    name: 'systems',
    display_name: 'Systems',
    description: 'Low-level systems programming persona. OS internals, memory allocators, network stacks, IPC mechanisms, kernel modules, and hardware-software interface design.',
    author_handle: 'ghost-frame',
    version: '1.9.0',
    tags: ['systems', 'linux', 'low-level'],
    conformance_score: 98,
    downloads: 13500,
    published_at: '2024-09-10T00:00:00Z',
    updated_at: '2025-04-30T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '1.9.0', published_at: '2025-04-30T00:00:00Z', changelog: 'io_uring patterns', downloads: 2200 },
      { version: '1.8.0', published_at: '2025-02-20T00:00:00Z', changelog: 'eBPF program scaffolding', downloads: 5100 },
      { version: '1.7.0', published_at: '2024-12-15T00:00:00Z', changelog: 'NUMA-aware allocator patterns', downloads: 6200 },
    ],
    capabilities: {
      languages: ['C', 'Rust', 'Assembly'],
      tools: ['strace_analyze', 'perf_stat', 'ebpf_scaffold'],
      memory: false,
      reasoning: 'hardware-aware',
      specialties: ['Linux kernel', 'io_uring', 'eBPF', 'memory allocators', 'POSIX IPC'],
    },
  },
  {
    name: 'testing',
    display_name: 'Testing',
    description: 'Quality assurance and test engineering persona. Test pyramid design, property-based testing, mutation testing, contract testing, and flaky test diagnosis.',
    author_handle: 'ghost-frame',
    version: '2.1.0',
    tags: ['testing', 'quality', 'tdd'],
    conformance_score: 95,
    downloads: 17300,
    published_at: '2024-09-25T00:00:00Z',
    updated_at: '2025-04-12T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '2.1.0', published_at: '2025-04-12T00:00:00Z', changelog: 'Pact contract testing patterns', downloads: 2700 },
      { version: '2.0.0', published_at: '2025-01-20T00:00:00Z', changelog: 'Mutation testing integration', downloads: 7200 },
      { version: '1.8.0', published_at: '2024-11-10T00:00:00Z', changelog: 'Property-based test strategies', downloads: 7400 },
    ],
    capabilities: {
      tools: ['mutation_test', 'coverage_map', 'flaky_detect', 'contract_verify'],
      memory: false,
      reasoning: 'adversarial-testing',
      specialties: ['TDD', 'BDD', 'property-based', 'contract testing', 'snapshot testing'],
    },
  },
  {
    name: 'unreal',
    display_name: 'Unreal',
    description: 'Unreal Engine development persona. Blueprint and C++ workflows, multiplayer netcode, Chaos physics, Nanite/Lumen rendering pipeline, and performance optimization for games.',
    author_handle: 'ghost-frame',
    version: '1.2.0',
    tags: ['unreal', 'gamedev', 'cpp'],
    conformance_score: 87,
    downloads: 10900,
    published_at: '2024-11-05T00:00:00Z',
    updated_at: '2025-03-18T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '1.2.0', published_at: '2025-03-18T00:00:00Z', changelog: 'UE 5.4 features', downloads: 2100 },
      { version: '1.1.0', published_at: '2025-01-10T00:00:00Z', changelog: 'Mass Entity system patterns', downloads: 4300 },
      { version: '1.0.0', published_at: '2024-11-05T00:00:00Z', changelog: 'Initial release', downloads: 4500 },
    ],
    capabilities: {
      languages: ['C++', 'Blueprint'],
      memory: true,
      reasoning: 'engine-aware',
      specialties: ['Blueprints', 'Chaos', 'Nanite', 'Lumen', 'GAS', 'multiplayer replication'],
    },
  },
  {
    name: 'writer',
    display_name: 'Writer',
    description: 'Technical writing and documentation persona. API references, architecture decision records, runbooks, tutorials, and changelog prose that developers actually read.',
    author_handle: 'ghost-frame',
    version: '1.9.0',
    tags: ['writing', 'docs', 'technical'],
    conformance_score: 92,
    downloads: 14200,
    published_at: '2024-09-01T00:00:00Z',
    updated_at: '2025-04-25T00:00:00Z',
    is_new: false,
    extends: undefined,
    versions: [
      { version: '1.9.0', published_at: '2025-04-25T00:00:00Z', changelog: 'Diagramming with Mermaid', downloads: 2100 },
      { version: '1.8.0', published_at: '2025-02-15T00:00:00Z', changelog: 'ADR template suite', downloads: 5800 },
      { version: '1.7.0', published_at: '2024-12-10T00:00:00Z', changelog: 'OpenAPI doc generation', downloads: 6300 },
    ],
    capabilities: {
      tools: ['openapi_doc', 'adr_template', 'changelog_format'],
      memory: true,
      reasoning: 'audience-aware',
      specialties: ['API docs', 'ADRs', 'runbooks', 'tutorials', 'changelogs', 'Ditatopics'],
    },
  },
];

export const MOCK_AUTHORS: AuthorRecord[] = [
  {
    handle: 'ghost-frame',
    display_name: 'ghost-frame',
    bio: 'Core FrameShift persona author. Maintains all official personas in the registry. Focused on precision, correctness, and zero-filler prompting.',
    packs: MOCK_PACKS,
    total_downloads: MOCK_PACKS.reduce((sum, p) => sum + p.downloads, 0),
    joined_at: '2024-07-01T00:00:00Z',
  },
];

export const ALL_TAGS: string[] = [
  'agents', 'analytics', 'appsec', 'architecture', 'auth', 'automation',
  'bots', 'ci-cd', 'cli', 'conversation', 'cpp', 'css',
  'data', 'design', 'desktop', 'devops', 'devtools', 'docs',
  'embeddings', 'experiments', 'frontend', 'gamedev', 'infrastructure',
  'linux', 'literature', 'low-level', 'lsp', 'memory', 'ml',
  'native', 'nlp', 'optimization', 'orchestration', 'performance',
  'policy', 'profiling', 'prototyping', 'protocols', 'quality',
  'rag', 'react', 'research', 'review', 'rust', 'security',
  'sql', 'systems', 'tdd', 'technical', 'testing', 'threats',
  'ui', 'unreal', 'writing',
];

export const SITE_STATS = {
  total_packs: MOCK_PACKS.length,
  total_downloads: MOCK_PACKS.reduce((sum, p) => sum + p.downloads, 0),
  total_authors: 1,
  avg_conformance: Math.round(MOCK_PACKS.reduce((sum, p) => sum + p.conformance_score, 0) / MOCK_PACKS.length),
};
